#The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
#This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 127.0.0.1

#Port to listen for new votes on
port: 8192

#Whether or not to print debug messages. In a production system, this should be set to false.
#This is useful when initially setting up NuVotifier to ensure votes are being delivered.
debug: false

#Setting this value to false will turn off the votifier port listening for external votes. This is beneficial if the server
#is only listening for votes coming a forwarding provider, like plugin messaging or a redis instance.
enableExternal: true

#All tokens, labeld by the serviceName of each server list.
tokens:
  #Default token for all server lists, if another isn't supplied.
  default: default

#Configuration section for all vote forwarding to NuVotifier
forwarding:
#Sets whether to set up a remote method for fowarding. Supported methods:
# none - Does not set up a forwarding method.
# pluginMessaging - Sets up the plugin messaging
  method: none
  pluginMessaging:
    channel: NuVotifier